= Kurstermine
ifndef::imagesdir[:imagesdir: images]
:icons: font
:experimental:
:sectnums:
:toc: left
:source-highlighter: rouge

== Description
Since some people have been dropping out of courses more and more often for some time now, which ultimately leads to allocated but unused places, a system is now needed that offers participants the opportunity to register for courses or withdraw from them independently, if the participant cannot appear on the scheduled date for any reason. When a person cancels an appointment, a person that didn't get a place can still register for the course to fill it up again.

== How to start
Follow the steps below to start the application:

* Go to the keycloak folder in your console.
[source, bash]
----
cd keycloak
----

* Start the keycloak server
[source, bash]
----
docker compose up
----

* Go to the backend folder in your console.
[source, bash]
----
cd backend
----

* Now you can start the quarkus app with the following command.
[source, bash]
----
mvn clean quarkus:dev
----

* Finally navigate into the frontend directory in a new terminal
[source, bash]
----
cd frontend
----

* Start the angular app
[source, bash]
----
ng serve
----

Now you will be able to see the frontend on http://localhost:4200

== Class Diagram
image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/2324-4bhif-syp/2324-4bhif-syp-project-kurstermine/main/asciidocs/docs/plantuml/cld.puml[]

== Use-Case Diagram
image::http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/2324-4bhif-syp/2324-4bhif-syp-project-kurstermine/main/asciidocs/docs/plantuml/ucd.puml[]