= Vierte Sprintplanung
ifndef::imagesdir[:imagesdir: images]
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
//:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/2324-4bhif-syp/2324-4bhif-syp-project-kurstermine/main/asciidocs/docs/mom/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/2324-4bhif-syp/2324-4bhif-syp-project-kurstermine] ‏ ‏ ‎
icon:home[link=https://htl-leonding.github.io/]
endif::backend-html5[]


.Teilnehmer
|===
|anwesend

|Herr Prof. Stütz

|Herr Prof. Aberger

|Winnie Ilming

|Moritz Gruber

|Lukas Sonnleitner

|Bajtik Berg
|===

.Ort und Zeit
[cols=2*]
|===
|Ort
|HTL Leonding, 4BHIF

|von-bis
|Di. 2023-12-12, 7. EH
|Dauer
|20 min
|===



== Besprochene Themen
* Deployment
* Workflow: Anmeldung eines Appointments => Bestätigung des Users erforderlich
* User aus Keycloak mit Customers aus Quarkus abstimmen



== Vereinbarungen und Entscheidungen

.Was wurde vereinbart?
[%autowidth]
|===
|wer |macht was |bis wann

| Hr. Ilming
a| link:https://vm81.htl-leonding.ac.at/agiles/99-373/current[Youtrack]
| 09.01.2024

| Hr. Gruber
a| link:https://vm81.htl-leonding.ac.at/agiles/99-373/current[Youtrack]
| 09.01.2024

| Hr. Sonnleitner
a| link:https://vm81.htl-leonding.ac.at/agiles/99-373/current[Youtrack]
| 09.01.2024

| Hr. Berg
a| link:https://vm81.htl-leonding.ac.at/agiles/99-373/current[Youtrack]
| 09.01.2024

|===
