@startuml
left to right direction

class Package {
}

class Appointment {
}

class Customer {
}

class Organisator {
}

class Instructor {
}

class Person {
}

package Keycloak {
    class K_User {
    }

    class K_Customer {
    }

    class K_Organisator {
    }

    class K_Instructor {
    }
}

K_Instructor -- K_User
K_Customer -- K_User
K_Organisator -- K_User

Package -left- Appointment
Package "*"--"1" Organisator: < owns
Instructor --|> Person
Customer --|> Person
Offer .. (Package, Appointment)
(Appointment, Instructor) .. AppointmentManagement
(Appointment, Customer) .. Participation
(Package, Customer) .. Purchase
(Person, Person) .. Relative

@enduml