name: Test Quarkus App
on:
  - push
  - pull_request
jobs:
  Test-Quarkus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: |
          chmod +x ./cicd/build.sh
          ./cicd/build.sh

      - name: Archive Project
        uses: actions/upload-artifact@v3
        with:
          name: Course-schedule
          path: dist/courseschedule.jar